config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :blogs
  devise_for :users, controllers: {registrations: 'registrations'}
  
  get 'events/welcome' => 'events#welcome'
  post 'events/event_subscription' => 'events#event_subscription'
  post 'events/event_going' => 'events#event_going'
  resources :events
  resources :preferences
  
  root 'events#welcome'

  get 'states/:country', to: 'events#states'
  get 'cities/:state/:country', to: 'events#cities'
  get 'departments/:stream_id', to: 'events#departments'

  get 'get_event_results/:query', to: 'events#get_event_results'
  get '/collegeda_admins', to: 'admins#collegeda_admins'
  get '/collegeda_users', to: 'admins#collegeda_users'
  get '/collegeda_events_moderation', to: 'admins#collegeda_events_moderation'
  get '/admins/publish_event', to: 'admins#publish_event'
  get '/collegeda_events_subscriber', to: 'admins#events_subscriber'
  get '/collegeda_events_action', to: 'admins#events_action'
  get '/collegeda_hide_events', to: 'admins#hide_events'
  get '/student_partner', to: 'events#student_partner'
  get '/about_us', to: 'events#about_us'
  get '/terms_and_conditions', to: 'events#terms_and_conditions'
  get '/privacy_policy', to: 'events#privacy_policy'

  get "sitemap.xml" => "sitemaps#index", :format => "xml", :as => :sitemap

  post '/process_notification', to: 'events#process_notification'
  post '/add_notification', to: 'events#add_notification'
  get '/event_user_preference', to: 'preferences#event_preference'
  get '/posted_events', to: "events#posted_events"
  get '/notifications', to: "events#notifications"
  post '/event_favourite', to: "events#event_favourite"
  get '/favourite_events', to: "events#favourite_events"

  namespace :api do
    namespace :v1 do
      get 'get_all_events' => 'events#events_list'
      get 'get_all_events_count' => 'events#events_count'
      get 'get_all_users_count' => 'events#all_users_count'
      post 'users/sign_in' => 'users#sign_in'
      get 'event_detail' => 'events#event_detail'
    end
  end

  resources :courses
  get '/internships/posted_internships', to: 'internships#posted_internships'
  resources :internships

  get '/apply_for_internship', to: 'internships#apply_for_internship'
  get '/all_events',  to: 'events#all_events'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :course_materials, dependent: :destroy

  accepts_nested_attributes_for :course_materials, reject_if: :all_blank, allow_destroy: true
end

app/models/event.rb
class Event < ActiveRecord::Base

 include ApplicationHelper
 belongs_to :user
 has_many :event_goings, dependent: :destroy
 belongs_to :event_detail, dependent: :destroy
 has_and_belongs_to_many :event_departments, dependent: :destroy
 has_many :event_contact_details, dependent: :destroy
 has_many :event_guest_details, dependent: :destroy
 belongs_to :event_url, dependent: :destroy
 has_and_belongs_to_many :event_extras, dependent: :destroy
 belongs_to :event_accomodation, dependent: :destroy
 belongs_to :event_banner, dependent: :destroy
 belongs_to :event_college_banner, dependent: :destroy
 belongs_to :event_broucher, dependent: :destroy
 has_many :event_sponsors, dependent: :destroy
 has_many :event_favourites, dependent: :destroy

 accepts_nested_attributes_for :event_detail, reject_if: :all_blank, allow_destroy: true
 accepts_nested_attributes_for :event_contact_details, reject_if: :all_blank, allow_destroy: true
 accepts_nested_attributes_for :event_guest_details, reject_if: :all_blank, allow_destroy: true
 accepts_nested_attributes_for :event_url, reject_if: :all_blank, allow_destroy: true
 accepts_nested_attributes_for :event_accomodation, reject_if: :all_blank, allow_destroy: true
 accepts_nested_attributes_for :event_banner, reject_if: :all_blank, allow_destroy: true
 accepts_nested_attributes_for :event_college_banner, reject_if: :all_blank, allow_destroy: true
 accepts_nested_attributes_for :event_broucher, reject_if: :all_blank, allow_destroy: true
 accepts_nested_attributes_for :event_sponsors, reject_if: :all_blank, allow_destroy: true
 accepts_nested_attributes_for :event_departments, reject_if: :all_blank, allow_destroy: true

 def to_param
    [id, event_name.parameterize, study_place.parameterize, district.parameterize].join("-")
 end
  
end

app/models/event_banner.rb
class EventBanner < ActiveRecord::Base
 has_one :event

 has_attached_file :banner, styles: {
    thumb: '150x150>',
  }

 validates_attachment_presence :banner
 validates_attachment_size :banner, :less_than => 5.megabytes
 validates_attachment_content_type :banner, :content_type => ['image/jpeg', 'image/png']
end

app/models/event_broucher.rb
class EventBroucher < ActiveRecord::Base
 has_one :event

 has_attached_file :broucher

validates_attachment_presence :broucher
validates_attachment_size :broucher, :less_than => 30.megabytes
validates_attachment_content_type :broucher, :content_type => ['application/pdf']
end

app/models/event_detail.rb
class EventDetail < ActiveRecord::Base
 has_one :event
end

app/models/event_extra.rb
class EventExtra < ActiveRecord::Base
end

app/models/event_going.rb
class EventGoing < ActiveRecord::Base
 belongs_to :user
 belongs_to :event
end

app/models/event_sponsor.rb
class EventSponsor < ActiveRecord::Base
 belongs_to :event

  has_attached_file :sponsor, styles: {
    thumb: '150x150>',
  }

validates_attachment_presence :sponsor
validates_attachment_size :sponsor, :less_than => 5.megabytes
validates_attachment_content_type :sponsor, :content_type => ['image/jpeg', 'image/png']
end

app/models/event_type.rb
class EventType < ActiveRecord::Base
 has_and_belongs_to_many :preferences
end

app/models/event_url.rb
class EventUrl < ActiveRecord::Base
 has_one :event
end

app/models/internship.rb
class Internship < ActiveRecord::Base
 belongs_to :job_type
 belongs_to :stipend_type
 belongs_to :stipend_amount
 has_many :applied_internships
 belongs_to :user

 accepts_nested_attributes_for :stipend_amount, reject_if: :all_blank, allow_destroy: true
end

app/models/job_type.rb
class JobType < ActiveRecord::Base
 has_one :internship
end

app/models/notification.rb
class Notification < ActiveRecord::Base
 belongs_to :event
end

app/models/preference.rb
class Preference < ActiveRecord::Base
 has_and_belongs_to_many :event_types
 has_and_belongs_to_many :event_departments
 has_many :location_preferences, dependent: :destroy

 accepts_nested_attributes_for :location_preferences, reject_if: :all_blank, allow_destroy: true
end

app/models/stipend_amount.rb
class StipendAmount < ActiveRecord::Base
 has_one :internship
end

app/models/stipend_type.rb
class StipendType < ActiveRecord::Base
 has_one :internship
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable, :lockable
  attr_accessor :current_password
  belongs_to :event_department
  belongs_to :event_department_stream
  validates :phone_no, :uniqueness => true, :allow_blank => true
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def disable_event_hide_btn event_id
    Event.find_by(id: event_id).is_published? ? "" : "disabled"
  end  

  def favourite_text event, user
    event.event_favourites.find_by(user_id: user.id).try(:is_favourite) == true ? "Remove from favourite" :
    "Add to favourite"
  end

  def favourite_class event, user
    event.event_favourites.find_by(user_id: user.id).try(:is_favourite) == true ? "btn-danger" :
    "btn-success"
  end

  def favourite_fa_icon event, user
    event.event_favourites.find_by(user_id: user.id).try(:is_favourite) == true ? "fa-heart" :
    "fa-heart-o"
  end
end

app/views/admins/collegeda_admins.html.erb
<br/>
<div style="text-align: center;">
  <button type="button" class="btn btn-warning btn-lg"><strong><%= link_to 'Events Moderation', collegeda_events_moderation_path,target: '_blank' %></strong></button>
</div>
<br/>

<br/>
<div style="text-align: center;">
  <button type="button" class="btn btn-info btn-lg"><strong><%= link_to 'All Users', collegeda_users_path,target: '_blank' %></strong></button>
</div>
<br/>

<br/>
<div style="text-align: center;">
  <button type="button" class="btn btn-danger btn-lg"><strong><%= link_to 'All Event Subscribers', collegeda_events_subscriber_path,target: '_blank' %></strong></button>
</div>
<br/>

<br/>
<div style="text-align: center;">
  <button type="button" class="btn btn-brown btn-lg"><strong><%= link_to 'Event Actions', collegeda_events_action_path,target: '_blank' %></strong></button>
</div>
<br/>

app/views/admins/collegeda_events_moderation.html.erb
<div class="container table-responsive">
  <% if Event.all.where(is_published: false).count == 0 %>
  <p> Waiting for first Event ! </p>
  <% else %>
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Event Name</th>
        <th>Live Zone</th>
      </tr>
    </thead>
    <tbody>
      <% Event.all.where(is_published: false).each do |event| %>
      <tr>
        <td><%= event.event_name %></td>
        <td><button type="button" class="btn btn-green"><strong><%= link_to 'Make It Live', admins_publish_event_path(event_id: event.id) %></strong></button></td>
      </tr>
      <% end %>
      
    </tbody>
  </table>
  <% end %>
</div>

app/views/admins/collegeda_users.html.erb
<div class="container table-responsive">
  <% if @users.count == 0 %>
  <p> Waiting for first User ! </p>
  <% else %>
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Phone #</th>
        <th>College</th>
        <th>Year of Study</th>
        <th>Email</th>
        <th>User Type</th>
        <th>Stream</th>
        <th>Department</th>
        <th>Offical email</th>
        <th>Company</th>
        <th>Know us</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name.present? ? user.name : "N/A" %></td>
        <td><%= user.phone_no.present? ? user.phone_no : "N/A" %></td>
        <td><%= user.place_of_study.present? ? user.place_of_study : "N/A" %></td>
        <td><%= user.passed_out_year.present? ? user.passed_out_year : "N/A" %></td>
        <td><%= user.email.present? ? user.email : "N/A" %></td>
        <td><%= user.registration_type.present? ? user.registration_type : "N/A" %></td>
        <td><%= user.event_department_stream.present? ? user.event_department_stream.name : "N/A" %></td>
        <td><%= user.event_department.present? ? user.event_department.name : "N/A" %></td>
        <td><%= user.official_email_id.present? ? user.official_email_id : "N/A" %></td>
        <td><%= user.company.present? ? user.company : "N/A" %></td>
        <td><%= user.know_us.present? ? user.know_us : "N/A" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <% end %>
</div>

app/views/admins/events_action.html.erb
<div class="container table-responsive">
  <% if Event.all.count == 0 %>
  <p> Waiting for first Event ! </p>
  <% else %>
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Event Name</th>
        <th>Update Event</th>
        <th>Hide Event</th>
        <th>Destroy Event</th>
      </tr>
    </thead>
    <tbody>
      <% Event.all.each do |event| %>
      <tr>
        <td><%= event.event_name %></td>
        <td><button type="button" class="btn btn-green"><strong><%= link_to 'Update', edit_event_path(event) %></strong></button></td>
        <td><button type="button" <%= disable_event_hide_btn(event.id) %> class="btn btn-info"><strong><%= link_to 'Hide', collegeda_hide_events_path(event_id: event.id) %></strong></button></td>
        <td>
          <button type="button" class="btn btn-danger"><strong><%= link_to 'Destroy', event_path(event),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></strong></button>
        </td>
      </tr>
      <% end %>
      
    </tbody>
  </table>
  <% end %>
</div>

app/views/admins/events_subscriber.html.erb
<div class="container table-responsive">
  <% if @event_subscribers.count == 0 %>
  <p> Waiting for first Subscriber ! </p>
  <% else %>
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Email</th>
        <th>User Name</th>
      </tr>
    </thead>
    <tbody>
      <% @event_subscribers.each do |subscribe| %>
      <tr>
        <td><%= subscribe.email_id %></td>
        <td><%= subscribe.user.name %></td>
      </tr>
      <% end %>
      
    </tbody>
  </table>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="google-site-verification" content="I1Ml8qheZbrL2Wq4qgYdekT5a-5-FmrrNUDinyIiWBY" />
    <meta name="description" content="A dedicated arena for facilitating College Students in Events Mgmt, Fresher Jobs, Internships and lots more..">
    <meta name="keywords" content="events, students partner, symposium, cultural events, events filtering, personalized notification, jobs, internships, faulty jobs">
    <meta name="author" content="">
    <title>Collegedaa</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
  <script src="https://js.pusher.com/4.0/pusher.min.js"></script>
    <%= csrf_meta_tags %>
</head>
  <body>
    
  <!--header section start-->
  <header class='first_section'>
    <div class='top_head'>
      <div class='container-fluid'>
        <div id="top_head_menu" class="dl-menuwrapper">
          <button class="dl-trigger">Open Menu</button>
          <ul class="dl-menu">
            <li><a href="/about_us">About Us</a></li>
            <li><a target="_blank" href="<%= student_partner_path %>">Student Partner</a></li>
            <li><a href="https://collegedaa.freshdesk.com/support/home" target="_blank">Support</a></li>
            <li><a href="/terms_and_conditions">Terms & Conditions</a></li>
            <li><a href="/privacy_policy">Privacy Policy</a></li>
            <div class='topheadmenu_social_icons'>
              <a class='socicons fb' target="_blank" href='http://www.facebook.com/collegedaa'><i class="fa fa-facebook" aria-hidden="true"></i></a>
              <a class='socicons twit' target="_blank" href='http://www.twitter.com/collegedaa'><i class="fa fa-twitter" aria-hidden="true"></i></a>
              <a class='socicons gp' target="_blank" href='https://plus.google.com/115172016622435313411'><i class="fa fa-google-plus" aria-hidden="true"></i></a>
              <a class='socicons lin' target="_blank" href='https://www.linkedin.com/company/collegedaa'><i class="fa fa-linkedin" aria-hidden="true"></i></a>
              <a class='socicons ins' target="_blank" href='http://www.instagram.com/collegedaa'><i class="fa fa-instagram" aria-hidden="true"></i></a>
              
            </div>    

           </ul>

        </div>

        <div class="topheadmenu_social_icons_right pull-right">
          <a class='socicons fb' target="_blank" href='http://www.facebook.com/collegedaa'><i class="fa fa-facebook" aria-hidden="true"></i></a>
          <a class='socicons twit' target="_blank" href='http://www.twitter.com/collegedaa'><i class="fa fa-twitter" aria-hidden="true"></i></a>
          <a class='socicons gp' target="_blank" href='https://plus.google.com/115172016622435313411'><i class="fa fa-google-plus" aria-hidden="true"></i></a>
          <a class='socicons lin' target="_blank" href='https://www.linkedin.com/company/collegedaa'><i class="fa fa-linkedin" aria-hidden="true"></i></a>
          <a class='socicons ins' target="_blank" href='http://www.instagram.com/collegedaa'><i class="fa fa-instagram" aria-hidden="true"></i></a>
        </div>
      </div>
    </div>

    <div class="container">
      <script>
      <% flash.each do |name, msg| %>
        ApplicationHelper.notify('<%= msg %>', '<%= name %>');
      <% end %>
    </script>
    </div>

    <div class='menu_logo_sec'>
      <div class="container-fluid">
        <div class="logo">
          <a href='/' title='Home'><img class='img-responsive' src='<%= asset_path('logo.png')%>'></a>
        </div>    
        
        <div role="navigation" class="navbar navbar-default pull-right mainmenu1">
          <div class="navbar-header">
            <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="collapse navbar-collapse pull-right">
            <ul class="nav navbar-nav">
              <li><a href="/events">Events</a></li>
              <% if user_signed_in? %><li><a href="/favourite_events">Favourite Events</a></li><% end %>
              <% if user_signed_in? %><li><a href="/posted_events">Posted Events</a></li><% end %>
              <% if user_signed_in? %>
               <li><a href="/event_user_preference">Event Preference</a></li>
              <% end %>
              <li><%= link_to 'Post Event', new_event_path %></li>
              <li><a target="_blank" href="<%= student_partner_path %>">Student Partner</a></li>
              <li><a href="https://collegedaa.freshdesk.com/support/home" target="_blank">Support</a></li>
              <li>
              <% if user_signed_in? and (Notification.where(user_id: current_user.id).count > 0) %>
                <a id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="/page.html"><i class="fa fa-bell-o fa-3" aria-hidden="true"></i></a>
                <ul class="dropdown-menu notifications notification_menu" id="notification" role="menu" aria-labelledby="dLabel">
                  <div class="notifications-wrapper">
                    
                      <% Notification.where(user_id: current_user.id).each do |notification| %>
                       <div class='notify_det'>
                      <div class='notifydet_left'>
                        <p><%= notification.try(:event).try(:event_name) %>, <%= notification.try(:event).try(:event_type) %>, <%= (Date.parse(notification.try(:event).try(:event_detail).try(:end_date).to_s.split(' ')[0]) - Date.parse(notification.try(:event).try(:event_detail).try(:start_date).to_s.split(' ')[0])).to_i+1 %> Days</p>
                        <p><%= notification.try(:event).try(:place_of_study) %></p>
                        <p><%= notification.try(:event).try(:district) %>, <%= notification.try(:event).try(:state) %>, <%= notification.try(:event).try(:country) %></p>
                        <p>Date: <%= notification.try(:event).try(:event_detail).try(:start_date).strftime("%a, %d %b %y") %> to <%= notification.try(:event).try(:event_detail).try(:end_date).strftime("%a, %d %b %y") %></p>
                        <!-- <p>www.collegedaa.com</p> -->
                      </div>
                      <div class='notifydet_right'>
                        <!-- <button class='delete_notify'>X</button> -->
                        <img src='<%= notification.try(:event).try(:event_college_banner).try(:college_banner).url %>'>
                        <%= link_to 'View', notification.try(:event) %>
                        <!-- <a href=''>View</a> -->
                      </div> 
                      </div>
                      <% end %>

                  </div>
                  <div class="notification-footer"><a href='/notifications'>View More</a></div>
                </ul>
                <% else %>
                <a id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="/page.html"><i class="fa fa-bell-o fa-3" aria-hidden="true"></i></a>
                <ul class="dropdown-menu notifications notification_menu" id="notification" role="menu" aria-labelledby="dLabel">
                  <div class="notifications-wrapper">
                  <div class='notify_det'>
                    <div class='notifydet_left'>
                    <p>Waiting for first notification.</p>
                   </div>
                  </div>
                 </div>
                 </ul> 
                <% end %>
              </li>

               <li>
                <a data-toggle="dropdown" class="dropdown-toggle" href="#"><%= user_signed_in? ? current_user.name+" " : "Sign In " %> <b class="caret"></b></a>
                <ul class="dropdown-menu multi-level">
                   <% if user_signed_in? %>
                    <li><%= link_to "Settings", edit_user_registration_path %></li>
                    <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                    <% else %>
                    <li><%= link_to "Sign In", new_user_session_path %></li>
                    <li><%= link_to "Sign Up", new_user_registration_path %></li>
                    <% end %>
                </ul>
              </li>
             </ul>
          </div>
        </div>
      </div>
    </div>    
  </header>    
<!--header section end-->

  
  <%= yield %>

    <!--footer section start-->
  <footer>
    <div class='footer_details'>
      <div class='container'>
        <div class='row'>
          <div class='col-md-3'>
            <div class='footer_sec1'>
              <h2>Quick Links</h2>
              <ul>
                <li><a href='/users/sign_up'>Signup</a></li>
                <li><a href='/events/new'>Post Event</a></li>
                <li><a href='/events'>Search Event</a></li>
                <li><a href="https://collegedaa.freshdesk.com/support/home" target="_blank">Support & Help</a></li>
              </ul>
            </div>
          </div>
          <div class='col-md-3'>
            <div class='footer_sec2'>
              <h2>Collegedaa</h2>
              <ul>
                <li><a href='/about_us'>About Us</a></li>
                <li><a href='/terms_and_conditions'>Terms & Conditions</a></li>
                <li><a href='/privacy_policy'>Privacy Policy</a></li>
              </ul>
            </div>
          </div>
          <div class='col-md-3'>
            <div class='footer_sec3'>
              <h2>Contact Us</h2>
              <a href="mailto:support@campusdaa.com?Subscribe to our Newsletter" target="_top">support@collegedaa.com</a>
            </div>
          </div>
          <div class='col-md-3'>
            <div class='footer_sec4'>

              <%= form_tag  events_event_subscription_path, {:id => 'subscribe_email', :class => 'form-horizontal', role: "form"} do %>
                 <h3><i class="fa fa-paper-plane" aria-hidden="true"></i>&nbsp;&nbsp; Subscribe to our newsletter</h3>
                <div class='fields'>
                  <input type="email" name="subscribe_email" value="" placeholder="Email Address" class="form-control validate[required]"/>
                  <% if current_user %>
                    <input type='submit' class='btn' value='Go'>
                  <% else %>
                    <input type='submit' class='btn' value='Go' disabled="disabled">
                  <% end %>
                </div>
              <% end %>


              <div class="footer_social">
                <a class='socicons fb' href='http://www.facebook.com/collegedaa' target='_blank'><i class="fa fa-facebook" aria-hidden="true"></i></a>
                <a class='socicons twit' href='http://www.twitter.com/collegedaa' target='_blank'><i class="fa fa-twitter" aria-hidden="true"></i></a>
                <a class='socicons gp' href='https://plus.google.com/115172016622435313411' target='_blank'><i class="fa fa-google-plus" aria-hidden="true"></i></a>
                <a class='socicons lin' href='https://www.linkedin.com/company/collegedaa' target='_blank'><i class="fa fa-linkedin" aria-hidden="true"></i></a>
                <a class='socicons ins' href='http://www.instagram.com/collegedaa' target='_blank'><i class="fa fa-instagram" aria-hidden="true"></i></a>
              </div><br/>
            </div>
          </div>
            <p style="font-size: 16px;text-align: center;">All the images used in this site are taken <a target="_blank" href="http://www.freepik.com">freepik.com</a>, for any other clarification include this conact us at support@collegedaa.com</p>
        </div>    
      </div>
    </div>
    <div class='footer'>
      <div class='container'>
        <p class='text-center'>@<%= Time.now.year %> Copyrights. All Rights Reserved.</p>
      </div>  
    </div>
  </footer>
<!--footer section end--> 

  </body>
</html>

<script type="text/javascript">
$(document).ready(function(){
    $("#subscribe_email").validationEngine();
});
</script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
 <script type="text/javascript">
$(document).ready(function() {
  $(".event_dept").select2({
   placeholder: "Select Departments"
  });
  $(".event_type_preferences").select2({
   placeholder: "Select Event Types"
  });
});
</script>

app/views/static_pages/about_us.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="google-site-verification" content="I1Ml8qheZbrL2Wq4qgYdekT5a-5-FmrrNUDinyIiWBY" />
  <title>About Us</title>
  <meta name="description" content="A dedicated arena for facilitating College Students in Events Mgmt, Fresher Jobs, Internships and lots more..">
    <meta name="keywords" content="events, students partner, symposium, cultural events, events filtering, personalized notification, jobs, internships, faulty jobs">

  <%= stylesheet_link_tag  'bootstrap.min' %>
  <%= stylesheet_link_tag  'static_pages_style' %>

  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Rancho&effect=shadow-multiple">
  <link href="https://fonts.googleapis.com/css?family=Lora" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Alegreya" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


</head>
<body>
  <header id="navigation" class="navbar-inverse navbar-fixed-top animated-header">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbarca">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class = "navbar-brand" href = "#">About Us</a>
      </div>
 
      <nav class="collapse navbar-collapse navbar-right" role="navigation" id="navbarca">
        <ul class="nav navbar-nav">
          <li><a href="/">Home</a></li>
          <li><a href="/student_partner">Student Partner</a></li>
          <li><a href="https://collegedaa.freshdesk.com/support/home">Support</a></li>
        </ul>
      </nav>
    </div>
  </header>

   
  <main class="site-content" role="main">
    <div id="ah">
      <div class="col-lg-12">
      </div>
    </div>

    <div id="join">
      <div class="container">
        <div class="row">
          <div class="c">
          <br>
          <br>
            Collegedaa.com is a platform a for showcasing your college events and pulling the crowd to your college event, getting internships, fresh jobs, faculty jobs, etc.
          </div>
        </div>
      </div>
    </div>

    <div class="row" id="about">
      <div class="col-sm-12 col-lg-6">
        <div class="h">
          MISSION
        </div>
        <div class="c">
          To be the best website for the student community across the world.
          <br>
          <br>
        </div>
      </div>

      <div class="col-sm-12 col-lg-6">
        <div class="h">
          VISION
        </div>
        <div class="c">
          To Build the biggest Global Student Community and exposing the real world to the student community.
          <br>
          <br>
        </div>
    </div>

  </main>          

</body>
</html>