config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :blogs
  devise_for :users, controllers: {registrations: 'registrations'}
  
  get 'events/welcome' => 'events#welcome'
  post 'events/event_subscription' => 'events#event_subscription'
  post 'events/event_going' => 'events#event_going'
  resources :events
  resources :preferences
  
  root 'events#welcome'

  get 'states/:country', to: 'events#states'
  get 'cities/:state/:country', to: 'events#cities'
  get 'departments/:stream_id', to: 'events#departments'

  get 'get_event_results/:query', to: 'events#get_event_results'
  get '/collegeda_admins', to: 'admins#collegeda_admins'
  get '/collegeda_users', to: 'admins#collegeda_users'
  get '/collegeda_events_moderation', to: 'admins#collegeda_events_moderation'
  get '/admins/publish_event', to: 'admins#publish_event'
  get '/collegeda_events_subscriber', to: 'admins#events_subscriber'
  get '/collegeda_events_action', to: 'admins#events_action'
  get '/collegeda_hide_events', to: 'admins#hide_events'
  get '/student_partner', to: 'events#student_partner'
  get '/about_us', to: 'events#about_us'
  get '/terms_and_conditions', to: 'events#terms_and_conditions'
  get '/privacy_policy', to: 'events#privacy_policy'

  get "sitemap.xml" => "sitemaps#index", :format => "xml", :as => :sitemap

  post '/process_notification', to: 'events#process_notification'
  post '/add_notification', to: 'events#add_notification'
  get '/event_user_preference', to: 'preferences#event_preference'
  get '/posted_events', to: "events#posted_events"
  get '/notifications', to: "events#notifications"
  post '/event_favourite', to: "events#event_favourite"
  get '/favourite_events', to: "events#favourite_events"

  namespace :api do
    namespace :v1 do
      get 'get_all_events' => 'events#events_list'
      get 'get_all_events_count' => 'events#events_count'
      get 'get_all_users_count' => 'events#all_users_count'
      post 'users/sign_in' => 'users#sign_in'
      get 'event_detail' => 'events#event_detail'
    end
  end

  resources :courses
  get '/internships/posted_internships', to: 'internships#posted_internships'
  resources :internships

  get '/apply_for_internship', to: 'internships#apply_for_internship'
  get '/all_events',  to: 'events#all_events'

end

app/models/internship.rb
class Internship < ActiveRecord::Base
 belongs_to :job_type
 belongs_to :stipend_type
 belongs_to :stipend_amount
 has_many :applied_internships
 belongs_to :user

 accepts_nested_attributes_for :stipend_amount, reject_if: :all_blank, allow_destroy: true
end

app/controllers/internships_controller.rb
class InternshipsController < ApplicationController
 def index
    @internships = Internship.all.order("created_at DESC")
    @applied_internships = AppliedInternship.find_by(company_id: current_user.id).present? ?
     AppliedInternship.where(company_id: current_user.id) : []
  end

  def show
    @internship = Internship.find(params[:id])
  end

  def new
    authenticate_user!
    @internship = Internship.new
    @internship.build_job_type
    @internship.build_stipend_type
    @internship.build_stipend_amount
  end

  def create
  @internship = Internship.new(internship_params)
  @internship.user_id = current_user.id
  respond_to do |format|
    if @internship.save
      format.html { redirect_to internships_path, :notice => "Successfully created internship" }
      format.js 
    else
      format.html { render :action => 'new' }
      format.js { render :action => 'new' }
    end
  end
 end

  def edit
    @internship = Internship.find(params[:id])
  end

  def update
    @internship = Internship.find(params[:id])
    @internship.user_id = current_user.id
    respond_to do |format|
    if @internship.update_attributes(internship_params)
      format.html { redirect_to internships_path, :notice => "Successfully updated internship" }
      format.js 
    else
      format.html { render :action => 'edit' }
      format.js { render :action => 'edit' }
    end
  end
  end

  def show
    @internship = Internship.find(params[:id])
  end

  def apply_for_internship
    authenticate_user!
    AppliedInternship.create(company_id: params[:company_id],user_id: current_user.id, internship_id: params[:internship_id], internship_status: 'Submitted')
    redirect_to :back
  end

  def posted_internships
    @posted_internships = Internship.where(user_id: current_user.id)
  end

private

  def internship_params
    params.require(:internship).permit(:title, :no_of_openings, :category, :start_date, 
    :country, :state, :district, :job_type_id, :duration, :skills, :stipend_type_id,
    :stipend_amount_id, :certificate, :pre_placement, :description, :user_id,
    stipend_amount_attributes: [:amount, :amount_lower_limit, :amount_upper_limit, :incentive_amount,
    :incentive_type, :id]
    ).tap do |attributes|
        attributes[:start_date] = parse_time(attributes[:start_date])
    end
  end

  def parse_time time
    Time.zone.parse(DateTime.strptime(time,"%m/%d/%Y %I:%M %P").to_s) if time.present?
  end
end

app/helpers/internships_helper.rb
module InternshipsHelper
  def check_internship_apply internship_id
    AppliedInternship.where(internship: internship_id, user_id: current_user.id).present? ? true : false
  end  
end

app/views/internships/_form.html.erb
<%= simple_form_for @internship,validate: true,remote: true, :authenticity_token => true, html: { multipart: true } do |f| %>
      <% if @internship.errors.any? %>
      <div id="errors">
        <h3><%= pluralize(@internship.errors.count, "error") %> prohibited this event from being saved:</h3>
        <ul>
          <% @internship.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
        </ul>
      </div>
      <% end %>
<!--post internship start-->
  <div id='internpost_body_container'>
    <div class='container-fluid'>
      <h2 class='text-center title'><span class='halfcolor'>Post Your</span> Summer Internship</h2>
      <form name='internpostform' id='internpostform' action='' method='post' enctype="multipart/form-data">
        <p class='text-center'>Hello! Welcome Aboard :D Please tell us about who you're looking for :)</p>
        <p class='text-center'>Please be flexible with your start date as interns from different colleges have vacations starting on different dates.</p>
        <div class='row'>
          <div class='col-md-4 form-group'>
            <label class='star_required'>Internship Title</label>
            <%= f.text_field :title, class: 'form-control validate[required, custom[onlyLetters]]', placeholder: "Internship Title", value: @internship.title %>
          </div>
          <div class='col-md-4 form-group'>
            <label class='star_required'>No of Openings</label>
            <%= f.text_field :no_of_openings, class: 'form-control validate[required, custom[onlyNumber]]', placeholder: "No of Openings in digits", value: @internship.no_of_openings %>
          </div>
          <div class='col-md-4 form-group'>
            <label class='star_required'>Category</label>
            <%= f.text_field :category, class: 'form-control', placeholder: "Category", value: @internship.category %>
          </div>
        </div>

        <div class='row'>
          <div class='col-md-4 form-group'>
            <div class='input-group date' id='internstartdate'>
              <label class='datelabel'>Start Date<span> *</span></label>
              <% date_val = @internship.start_date.present? ? @internship.start_date.strftime("%m/%d/%Y %I:%M %p") : "" %>
              <%= f.text_field :start_date, placeholder: "Start Date", class: "form-control validate[required]", value: date_val %>
              <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
            </div>
          </div>
          <div class='col-md-4 form-group'>
            <label class='star_required'>Duration</label>
            <%= f.text_field :duration, class: 'form-control validate[required, custom[onlyNumber]]', placeholder: "Duration (in months) in digits", value: @internship.duration %>
          </div>

          <div class='col-md-4 form-group'>
            <label class='star_required'>Job Type</label>
            <%= f.collection_select :job_type_id, JobType.all, :id, :name, { selected: @internship.job_type_id, prompt: "Select Job Type" }, class: "select2-size form-control validate[required] select2-offscreen" %>
          </div>
        </div>

        <div class="row">
        <div class='col-md-4 form-group'>
        <label class='star_required'>Country</label>
         <%= select_tag "internship[country]", options_for_select(CS.countries.slice(:AU, :CA, :IN, :US, :GB).map { |obj| [obj[1], obj[0]] }, @internship.country), class: "select2-size form-control validate[required] select2-offscreen country", prompt: "Select Country" %>
        </div>
        <div class='col-md-4 form-group'>
        <label class='star_required'>State</label>
          <%= select_tag "internship[state]", options_for_select(@internship.state.present? ? [@internship.state] : [], @internship.state), prompt: "Select State", class: "select2-size form-control validate[required] select2-offscreen state" %>
        </div>
        <div class='col-md-4 form-group'>
        <label class='star_required'>District</label>
           <%= select_tag "internship[district]", options_for_select(@internship.district.present? ? [@internship.district] : [], @internship.district), prompt: "Select City", class: "select2-size validate[required] form-control select2-offscreen city" %>
        </div>
        </div>

        <div class='row'>
          <div class='col-md-4 form-group'>
            <label class='star_required'>Skills</label>
            <%= f.text_field :skills, class: 'form-control', placeholder: "Enter skills", value: @internship.skills %>
          </div>
          <div class='col-md-4 form-group'>
            <label class='star_required'>Stipend Type</label>
            <%= f.collection_select :stipend_type_id, StipendType.all, :id, :name, { selected: @internship.stipend_type_id, prompt: "Select Stipend Type" }, class: "select2-size form-control validate[required] select2-offscreen" %>
          </div>
        </div>

        <%= f.simple_fields_for :stipend_amount do |stipend_amount| %>
          <%= render 'stipend_amount_fields', f: stipend_amount %>
        <% end %>

        <div class='row'>
          <div class='col-md-12 form-group'>
            <%= f.check_box :certificate %> Certificate/LOR will be provided<br/>
            <%= f.check_box :pre_placement %> Pre Placement Offer could be made
          </div>
        </div>
        
        <div class='row'>
          <div class='col-md-12 form-group'>
            <label class='star_required'>Description</label><br/>
            <%= f.text_area :description, rows: '8', cols: '81.9', class: "validate[required]" %>
          </div>
        </div>

        <input type='submit' name='internpost_submit' class='internpost_submit btn btn-success' value='Submit'>
      </form>
    </div>
  </div> 
 <% end %>  
<!--post internship end-->

<script type="text/javascript">
    $(".internpost_submit").click(function(e){
 e.preventDefault();
 swal({   title: "Attention",   text: "This internship is submitted for moderation and will be published soon !",   type: "info",   showCancelButton: true,   confirmButtonColor: "#DD6B55",   confirmButtonText: "Okies!",   closeOnConfirm: false }, function(){ $(".edit_internship, #new_internship").submit(); });

});

  $(function () {
  
  $("#new_internship").validationEngine({
    promptPosition : "bottomLeft",
    autoHidePrompt: true,
    autoHideDelay: 3000,
    fadeDuration: 0.3,
    scroll: false,
    maxErrorsPerField:1
  });

  });
</script>

app/views/internships/_stipend_amount_fields.html.erb
<div class='stipendtype_fixed'>
  <div class='row'>
    <div class='col-md-4 form-group'>
      <label class='star_required'>Amount</label>
      <%= f.text_field :amount, class: 'form-control validate[required, custom[onlyNumber]]', placeholder: "Put Stipend here in digits", value: @internship.stipend_amount.try(:amount) %>
    </div>
  </div>
</div>

<div class='stipendtype_variable'>
  <div class='row'>
    <div class='col-md-4 form-group'>
      <label class='star_required'>Amount(Lower Limit)</label>
      <%= f.text_field :amount_lower_limit, class: 'form-control validate[required, custom[onlyNumber]]', placeholder: "Put Lower Limit here in digits", value: @internship.stipend_amount.try(:amount_lower_limit) %>
    </div>
    <div class='col-md-4 form-group'>
      <label class='star_required'>Amount(Upper Limit)</label>
      <%= f.text_field :amount_upper_limit, class: 'form-control validate[required, custom[onlyNumber]]', placeholder: "Put Upper Limit here in digits", value: @internship.stipend_amount.try(:amount_upper_limit) %>
    </div>
  </div>
</div>

<div class='stipendtype_incentive'>
  <div class='row'>
    <div class='col-md-4 form-group'>
      <label class='star_required'>Incentive amount</label>
      <%= f.text_field :incentive_amount, class: 'form-control validate[required, custom[onlyNumber]]', placeholder: "Put Incentive here in digits", value: @internship.stipend_amount.try(:incentive_amount) %>
    </div>
    <div class='col-md-4 form-group'>
      <label class='star_required'>Incentive Type</label>
      <%= f.text_field :incentive_type, class: 'form-control validate[required, custom[onlyNumber]]', placeholder: "Put Incentive Type here in digits", value: @internship.stipend_amount.try(:incentive_type) %>
    </div>
  </div>
</div>

app/views/internships/create.js.erb
toastr.info('Successfully created Internship!')
window.location.href = "/internships";

app/views/internships/edit.html.erb
<div class="container">
<%= "Editing #{@internship.title}" %>
<%= render "form" %>
</div>
<script>
 $(document).ready(function(){
  $("#internship_stipend_type_id").click();
 });
</script>

app/views/internships/index.html.erb
<div class="container">
<% if current_user.registration_type.include?("Employer") %>
 <%= link_to "New Internship", new_internship_path %>
 <%= link_to "Posted Internship", internships_posted_internships_path %>
 <br>Dashboard (Showing applied candidates)
<% @applied_internships.each do |internship| %>
  <p><%= internship.user.name %></p>
  <p>Applied for: <%= internship.internship.title %></p>
  <p><%= internship.internship_status %></p>
  <p>-------------------------------------------</p>
<% end %>
<% elsif current_user.registration_type.include?("Student-Studying") || current_user.registration_type.include?("Student-Passout") %>
 <% @internships.each do |internship| %>
  <p><%= link_to internship.title, internship %></p>
 <% end %> 
<% end %>

</div>

app/views/internships/new.html.erb
<div class="container">
<h3> New Internship</h3>
<%= render "form" %>
</div>

app/views/internships/posted_internships.html.erb
<div class="container">
<% @posted_internships.each do |internship| %>
  <p><%= internship.title.html_safe %>
  </p>
  <p>-------------------------------------------</p>
<% end %>
</div>

app/views/internships/show.html.erb
<div class="container">
Show page  
  <p><%= @internship.title.html_safe %></p>
  <p><%= @internship.no_of_openings %></p>
  <p><%= @internship.category %></p>
  <p><%= @internship.start_date %></p>
  <p><%= link_to check_internship_apply(@internship.id) == true ? "Applied" : "Apply", apply_for_internship_path(internship_id: @internship.id, company_id: @internship.user_id), class: "btn btn-primary", disabled: check_internship_apply(@internship.id) %></p>
  <p>-------------------------------------------</p>
</div>

app/views/internships/update.js.erb
toastr.info('Successfully updated Internship!')
window.location.href = "/internships";